### ISSUE TITLE
your api goes down every few requests.

### ISSUE THREAD

**Issue by ghost** [lancewboettcher/KitchenPointers#1]
one minute it works fine, then perfectly valid (and before working) requests return only 404.

**Comment by ghost** [comment]
![screenshot from 2015-12-09 18 54 00](https://cloud.githubusercontent.com/assets/7045383/11694011/28966774-9ea8-11e5-9b5c-b3f7f75d525b.png)
![screenshot from 2015-12-09 19 04 54](https://cloud.githubusercontent.com/assets/7045383/11694012/28b6aa7a-9ea8-11e5-9522-3a38d7d4cd26.png)

all that changed between these two requests is the time. exactly the same request, but sometimes it works, other times it 404s.

**Comment by lancewboettcher** [comment]
There was an issue with DB connections not being closed and it would reach the max connections. Fixed and uploaded the new build.
